name: API Tests

on:
  push:
    branches: [ dev ]
    paths:
      - 'src/api/**'
      - 'tests/api/**'
      - 'requirements.txt'
      - '.github/workflows/api-tests.yml'
  pull_request:
    branches: [ dev ]
    paths:
      - 'src/api/**'
      - 'tests/api/**'
      - 'requirements.txt'
      - '.github/workflows/api-tests.yml'
  workflow_dispatch:

jobs:
  setup:
    uses: ./.github/workflows/reusable-setup.yml
    with:
      python-version: "3.12"
      install-dependencies: true
      install-dev-dependencies: true

  api-tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Run API tests
      run: |
        pytest tests/api/ \
          --cov=src/api \
          --cov-report=xml \
          --cov-report=term-missing \
          --cov-fail-under=90
    
    - name: Upload coverage
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: api-tests
        name: codecov-api
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
