name: Reusable Python Setup

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.12"
      install-dependencies:
        required: false
        type: boolean
        default: true
      install-dev-dependencies:
        required: false
        type: boolean
        default: false

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: 'pip'
      
      - name: Install system dependencies
        if: inputs.install-dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg2
      
      - name: Install Python dependencies
        if: inputs.install-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Install development dependencies
        if: inputs.install-dev-dependencies
        run: |
          pip install pytest pytest-cov pytest-xdist pytest-asyncio
          pip install black flake8 mypy types-all
          pip install bandit safety
