name: Security Scan

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sundays
  workflow_dispatch:

jobs:
  setup:
    uses: ./.github/workflows/reusable-setup.yml
    with:
      python-version: "3.12"
      install-dependencies: true
      install-dev-dependencies: true

  security:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Run Bandit security scan
      run: |
        bandit -r src/ -f txt -o security-report.txt
        
    - name: Check dependencies
      run: |
        safety check -r requirements.txt --full-report --output text > dependencies-report.txt

    - name: Upload security results
      uses: actions/upload-artifact@v4
      with:
        name: security-reports
        path: |
          security-report.txt
          dependencies-report.txt
        retention-days: 30
